{{- /*
ConfigMap for OPC UA Server Configuration
Because environment variables for JSON is masochism
*/ -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "emberburn.fullname" . }}-config
  labels:
    {{- include "emberburn.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "tags": {{ .Values.config.tags | toJson }},
      "publishers": {{ .Values.config.publishers | toJson }}
    }
