apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "emberburn.publishersConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "emberburn.labels" . | nindent 4 }}
data:
  publishers.json: |
    {{- include "emberburn.publishersConfig" . | nindent 4 }}
